database:
  mysql:
    dns:

jwt:
  timeout: 86400s


default_password: Admin@123

etcd:
  endpoints:
    - 127.0.0.1:2379

kafka:
  brokers:
    - 127.0.0.1:9092
  async: false
  topics:
    - test_topic
    - order_created